### ISSUE TITLE
Document Edit Sync not working correctly

### ISSUE THREAD

**Issue by BoykoAlex** [gtache/intellij-lsp#16]
There is an LSP that works fine for doc edits sync with VSCode, Atom and Eclipse (LSP4E), but not working with IntelliJ client.
After a couple of simple edits i could see with the debugger the document on the server having content different from whats in the IntelliJ editor on the client.
After a bit of investigation i think problematic piece is:
https://github.com/gtache/intellij-lsp/blob/master/intellij-lsp/src/com/github/gtache/lsp/editor/EditorEventManager.scala#L484
It should be the length of the text being replaced, i.e should be `event.getOldLength`
See https://microsoft.github.io/language-server-protocol/specification#textDocument_didChange

I think this change should help with my use case. (To confirm later)

**Comment by martinlippert** [comment]
Looks like this PR is related: https://github.com/gtache/intellij-lsp/pull/18

**Comment by gtache** [comment]
The PR should have fixed it, I'll let it open while awaiting confirmation that it is indeed the case.
