### ISSUE TITLE
IllegalCharacterException when space in path

### ISSUE THREAD

**Issue by apupier** [gtache/intellij-lsp#17]
- install the LSP plugin
- create a project in workspace with a name containign space
- in settings, try to add a server

> Illegal character in path at index 59: file://C:/git/camel-language-server/clients/IntelliJ/Apache Camel LSP Client/.idea/workspace.xml
> java.net.URISyntaxException: Illegal character in path at index 59: file://C:/git/camel-language-server/clients/IntelliJ/Apache Camel LSP Client/.idea/workspace.xml
> 	at java.net.URI$Parser.fail(URI.java:2848)
> 	at java.net.URI$Parser.checkChars(URI.java:3021)
> 	at java.net.URI$Parser.parseHierarchical(URI.java:3105)
> 	at java.net.URI$Parser.parse(URI.java:3053)
> 	at java.net.URI.<init>(URI.java:588)
> 	at java.net.URL.toURI(URL.java:946)
> 	at com.github.gtache.lsp.utils.FileUtils$.VFSToURI(FileUtils.scala:76)
> 	at com.github.gtache.lsp.requests.FileEventManager$.fileChanged(FileEventManager.scala:41)
> 	at com.github.gtache.lsp.editor.listeners.VFSListener$.contentsChanged(VFSListener.scala:26)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at com.intellij.util.EventDispatcher.dispatch(EventDispatcher.java:99)
> 	at com.intellij.util.EventDispatcher.access$200(EventDispatcher.java:35)
> 	at com.intellij.util.EventDispatcher$2.invoke(EventDispatcher.java:79)
> 	at com.sun.proxy.$Proxy18.contentsChanged(Unknown Source)
> 	at com.intellij.openapi.vfs.impl.BulkVirtualFileListenerAdapter.fireAfter(BulkVirtualFileListenerAdapter.java:65)
> 	at com.intellij.openapi.vfs.impl.BulkVirtualFileListenerAdapter.after(BulkVirtualFileListenerAdapter.java:56)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at com.intellij.util.messages.impl.MessageBusConnectionImpl.deliverMessage(MessageBusConnectionImpl.java:117)
> 	at com.intellij.util.messages.impl.MessageBusImpl.doPumpMessages(MessageBusImpl.java:449)
> 	at com.intellij.util.messages.impl.MessageBusImpl.pumpWaitingBuses(MessageBusImpl.java:410)
> 	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:399)
> 	at com.intellij.util.messages.impl.MessageBusImpl.sendMessage(MessageBusImpl.java:380)
> 	at com.intellij.util.messages.impl.MessageBusImpl.access$200(MessageBusImpl.java:45)
> 	at com.intellij.util.messages.impl.MessageBusImpl$2.invoke(MessageBusImpl.java:231)
> 	at com.sun.proxy.$Proxy16.after(Unknown Source)
> 	at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSImpl$2.close(PersistentFSImpl.java:651)
> 	at sun.nio.cs.StreamEncoder.implClose(StreamEncoder.java:320)
> 	at sun.nio.cs.StreamEncoder.close(StreamEncoder.java:149)
> 	at java.io.OutputStreamWriter.close(OutputStreamWriter.java:233)
> 	at com.intellij.openapi.util.JDOMUtil.write(JDOMUtil.java:384)
> 	at com.intellij.configurationStore.FileBasedStorageKt$doWrite$$inlined$runUndoTransparentWriteAction$1$1.compute(actions.kt:76)
> 	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:1015)
> 	at com.intellij.configurationStore.FileBasedStorageKt$doWrite$$inlined$runUndoTransparentWriteAction$1.run(actions.kt:29)
> 	at com.intellij.openapi.command.impl.CoreCommandProcessor.runUndoTransparentAction(CoreCommandProcessor.java:323)
> 	at com.intellij.configurationStore.FileBasedStorageKt.doWrite(FileBasedStorage.kt:295)
> 	at com.intellij.configurationStore.FileBasedStorageKt.writeFile(FileBasedStorage.kt:202)
> 	at com.intellij.configurationStore.FileBasedStorage$FileSaveSession.saveLocally(FileBasedStorage.kt:100)
> 	at com.intellij.configurationStore.XmlElementStorage$XmlElementStorageSaveSession.save(XmlElementStorage.kt:151)
> 	at com.intellij.configurationStore.FileBasedStorage$FileSaveSession.save(FileBasedStorage.kt:85)
> 	at com.intellij.configurationStore.ComponentStoreImplKt.executeSave(ComponentStoreImpl.kt:486)
> 	at com.intellij.configurationStore.ComponentStoreImpl.doSave(ComponentStoreImpl.kt:239)
> 	at com.intellij.configurationStore.ProjectStoreImpl.doSave(ProjectStoreImpl.kt:335)
> 	at com.intellij.configurationStore.ComponentStoreImpl.save(ComponentStoreImpl.kt:196)
> 	at com.intellij.openapi.components.impl.stores.StoreUtil.save(StoreUtil.java:49)
> 	at com.intellij.openapi.project.impl.ProjectImpl.save(ProjectImpl.java:349)
> 	at com.intellij.openapi.components.impl.stores.StoreUtil.saveDocumentsAndProjectsAndApp(StoreUtil.java:126)
> 	at com.intellij.openapi.application.impl.ApplicationImpl.saveAll(ApplicationImpl.java:1413)
> 	at com.intellij.ide.SaveAndSyncHandlerImpl.saveProjectsAndDocuments(SaveAndSyncHandlerImpl.java:126)
> 	at com.intellij.ide.SaveAndSyncHandlerImpl$2.lambda$onFrameDeactivated$0(SaveAndSyncHandlerImpl.java:94)
> 	at com.intellij.openapi.application.TransactionGuardImpl.runSyncTransaction(TransactionGuardImpl.java:88)
> 	at com.intellij.openapi.application.TransactionGuardImpl.lambda$submitTransaction$1(TransactionGuardImpl.java:111)
> 	at com.intellij.openapi.application.TransactionGuardImpl.submitTransaction(TransactionGuardImpl.java:120)
> 	at com.intellij.openapi.application.TransactionGuard.submitTransaction(TransactionGuard.java:122)
> 	at com.intellij.ide.SaveAndSyncHandlerImpl$2.onFrameDeactivated(SaveAndSyncHandlerImpl.java:92)
> 	at com.intellij.ide.FrameStateManagerImpl.fireDeactivationEvent(FrameStateManagerImpl.java:84)
> 	at com.intellij.ide.FrameStateManagerImpl.access$500(FrameStateManagerImpl.java:32)
> 	at com.intellij.ide.FrameStateManagerImpl$2.lambda$applicationDeactivated$0(FrameStateManagerImpl.java:70)
> 	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:246)
> 	at com.intellij.util.Alarm$Request.runSafely(Alarm.java:417)
> 	at com.intellij.util.Alarm$Request.access$700(Alarm.java:344)
> 	at com.intellij.util.Alarm$Request$1.run(Alarm.java:384)
> 	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:315)
> 	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:424)
> 	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:407)
> 	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
> 	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
> 	at java.awt.EventQueue.access$500(EventQueue.java:98)
> 	at java.awt.EventQueue$3.run(EventQueue.java:715)
> 	at java.awt.EventQueue$3.run(EventQueue.java:709)
> 	at java.security.AccessController.doPrivileged(Native Method)
> 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
> 	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
> 	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:822)
> 	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:650)
> 	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:366)
> 	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
> 	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
> 	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
> 	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
> 	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
> 	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by apupier** [comment]
another stack:

> Illegal character in path at index 24: file://C:/Users/Aurelien Pupier/.IdeaIC2017.3/config/options/recentProjects.xml
> java.net.URISyntaxException: Illegal character in path at index 24: file://C:/Users/Aurelien Pupier/.IdeaIC2017.3/config/options/recentProjects.xml
> 	at java.net.URI$Parser.fail(URI.java:2848)
> 	at java.net.URI$Parser.checkChars(URI.java:3021)
> 	at java.net.URI$Parser.parseHierarchical(URI.java:3105)
> 	at java.net.URI$Parser.parse(URI.java:3053)
> 	at java.net.URI.<init>(URI.java:588)
> 	at java.net.URL.toURI(URL.java:946)
> 	at com.github.gtache.lsp.utils.FileUtils$.VFSToURI(FileUtils.scala:76)
> 	at com.github.gtache.lsp.requests.FileEventManager$.fileChanged(FileEventManager.scala:41)
> 	at com.github.gtache.lsp.editor.listeners.VFSListener$.contentsChanged(VFSListener.scala:26)
> 	at sun.reflect.GeneratedMethodAccessor75.invoke(Unknown Source)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at com.intellij.util.EventDispatcher.dispatch(EventDispatcher.java:99)
> 	at com.intellij.util.EventDispatcher.access$200(EventDispatcher.java:35)
> 	at com.intellij.util.EventDispatcher$2.invoke(EventDispatcher.java:79)
> 	at com.sun.proxy.$Proxy18.contentsChanged(Unknown Source)
> 	at com.intellij.openapi.vfs.impl.BulkVirtualFileListenerAdapter.fireAfter(BulkVirtualFileListenerAdapter.java:65)
> 	at com.intellij.openapi.vfs.impl.BulkVirtualFileListenerAdapter.after(BulkVirtualFileListenerAdapter.java:56)
> 	at sun.reflect.GeneratedMethodAccessor74.invoke(Unknown Source)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at com.intellij.util.messages.impl.MessageBusConnectionImpl.deliverMessage(MessageBusConnectionImpl.java:117)
> 	at com.intellij.util.messages.impl.MessageBusImpl.doPumpMessages(MessageBusImpl.java:449)
> 	at com.intellij.util.messages.impl.MessageBusImpl.pumpWaitingBuses(MessageBusImpl.java:410)
> 	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:399)
> 	at com.intellij.util.messages.impl.MessageBusImpl.sendMessage(MessageBusImpl.java:380)
> 	at com.intellij.util.messages.impl.MessageBusImpl.access$200(MessageBusImpl.java:45)
> 	at com.intellij.util.messages.impl.MessageBusImpl$2.invoke(MessageBusImpl.java:231)
> 	at com.sun.proxy.$Proxy16.after(Unknown Source)
> 	at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSImpl$2.close(PersistentFSImpl.java:651)
> 	at sun.nio.cs.StreamEncoder.implClose(StreamEncoder.java:320)
> 	at sun.nio.cs.StreamEncoder.close(StreamEncoder.java:149)
> 	at java.io.OutputStreamWriter.close(OutputStreamWriter.java:233)
> 	at com.intellij.openapi.util.JDOMUtil.write(JDOMUtil.java:384)
> 	at com.intellij.configurationStore.FileBasedStorageKt$doWrite$$inlined$runUndoTransparentWriteAction$1$1.compute(actions.kt:76)
> 	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:1015)
> 	at com.intellij.configurationStore.FileBasedStorageKt$doWrite$$inlined$runUndoTransparentWriteAction$1.run(actions.kt:29)
> 	at com.intellij.openapi.command.impl.CoreCommandProcessor.runUndoTransparentAction(CoreCommandProcessor.java:323)
> 	at com.intellij.configurationStore.FileBasedStorageKt.doWrite(FileBasedStorage.kt:295)
> 	at com.intellij.configurationStore.FileBasedStorageKt.writeFile(FileBasedStorage.kt:202)
> 	at com.intellij.configurationStore.FileBasedStorage$FileSaveSession.saveLocally(FileBasedStorage.kt:100)
> 	at com.intellij.configurationStore.XmlElementStorage$XmlElementStorageSaveSession.save(XmlElementStorage.kt:151)
> 	at com.intellij.configurationStore.FileBasedStorage$FileSaveSession.save(FileBasedStorage.kt:85)
> 	at com.intellij.configurationStore.ComponentStoreImplKt.executeSave(ComponentStoreImpl.kt:486)
> 	at com.intellij.configurationStore.ComponentStoreImpl.doSave(ComponentStoreImpl.kt:239)
> 	at com.intellij.configurationStore.ComponentStoreImpl.save(ComponentStoreImpl.kt:196)
> 	at com.intellij.openapi.components.impl.stores.StoreUtil.save(StoreUtil.java:49)
> 	at com.intellij.openapi.application.impl.ApplicationImpl.saveSettings(ApplicationImpl.java:1401)
> 	at com.intellij.openapi.components.impl.stores.StoreUtil.saveDocumentsAndProjectsAndApp(StoreUtil.java:129)
> 	at com.intellij.openapi.application.impl.ApplicationImpl.saveAll(ApplicationImpl.java:1413)
> 	at com.intellij.ide.SaveAndSyncHandlerImpl.saveProjectsAndDocuments(SaveAndSyncHandlerImpl.java:126)
> 	at com.intellij.ide.SaveAndSyncHandlerImpl$2.lambda$onFrameDeactivated$0(SaveAndSyncHandlerImpl.java:94)
> 	at com.intellij.openapi.application.TransactionGuardImpl.runSyncTransaction(TransactionGuardImpl.java:88)
> 	at com.intellij.openapi.application.TransactionGuardImpl.lambda$submitTransaction$1(TransactionGuardImpl.java:111)
> 	at com.intellij.openapi.application.TransactionGuardImpl.submitTransaction(TransactionGuardImpl.java:120)
> 	at com.intellij.openapi.application.TransactionGuard.submitTransaction(TransactionGuard.java:122)
> 	at com.intellij.ide.SaveAndSyncHandlerImpl$2.onFrameDeactivated(SaveAndSyncHandlerImpl.java:92)
> 	at com.intellij.ide.FrameStateManagerImpl.fireDeactivationEvent(FrameStateManagerImpl.java:84)
> 	at com.intellij.ide.FrameStateManagerImpl.access$500(FrameStateManagerImpl.java:32)
> 	at com.intellij.ide.FrameStateManagerImpl$2.lambda$applicationDeactivated$0(FrameStateManagerImpl.java:70)
> 	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:246)
> 	at com.intellij.util.Alarm$Request.runSafely(Alarm.java:417)
> 	at com.intellij.util.Alarm$Request.access$700(Alarm.java:344)
> 	at com.intellij.util.Alarm$Request$1.run(Alarm.java:384)
> 	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:315)
> 	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:424)
> 	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:407)
> 	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
> 	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
> 	at java.awt.EventQueue.access$500(EventQueue.java:98)
> 	at java.awt.EventQueue$3.run(EventQueue.java:715)
> 	at java.awt.EventQueue$3.run(EventQueue.java:709)
> 	at java.security.AccessController.doPrivileged(Native Method)
> 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
> 	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
> 	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:822)
> 	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:650)
> 	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:366)
> 	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
> 	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
> 	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
> 	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
> 	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
> 	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by bbarker** [comment]
+1

**Comment by gtache** [comment]
This should be fixed in 1.4.0, thanks for the report!
