### ISSUE TITLE
Illegal character in path exception if spaces in path to project.

### ISSUE THREAD

**Issue by nlabhishetty** [gtache/intellij-lsp#22]
LSP Support plugin is giving an exception if there are spaces in the name of any directory in the path to the current project.

**Comment by ShrykeWindgrace** [comment]
Similarly, if there are spaces in paths to config files of Idea itself, the plugin crashes, too. E.g.
`Illegal character in path at index 62: file:/data/homes/username/.IdeaIC2017.3/config/keymaps/Default copy.xml`

**Comment by gtache** [comment]
Duplicate of #17 , this should be fixed in 1.4.0
