### ISSUE TITLE
NPE at EditorEventManager.scala:326

### ISSUE THREAD

**Issue by manwithafox** [gtache/intellij-lsp#24]
For keyword completion items, lookupElementBuilder is null - obviously: 

           var lookupElementBuilder: LookupElementBuilder = null
                        /*.withRenderer((element: LookupElement, presentation: LookupElementPresentation) => { //TODO later
                      presentation match {
                        case realPresentation: RealLookupElementPresentation =>
                          if (!realPresentation.hasEnoughSpaceFor(presentation.getItemText, presentation.isItemTextBold)) {
                          }
                      }
                    })*/
            if (kind == CompletionItemKind.Keyword) lookupElementBuilder.withBoldness(true)

**Comment by gtache** [comment]
Fixed in 1.4.0, thanks !
