### ISSUE TITLE
is it possible for a single language server to handle multiple extensions?

### ISSUE THREAD

**Issue by cspotcode** [gtache/intellij-lsp#26]
In a Typescript project, the language server handles `.d.ts`, `.ts`, and `.js` files.  So a single language server instance will need to be launched for all 3.  I'm not sure if that can be configured; it looks like we are limited to one extension per server.

**Comment by gtache** [comment]
This has been added in the release which should be available in ~2 days, you simply have to separate the extensions with a semicolon (which would give ts;js) in your case.

**Comment by cspotcode** [comment]
@gtache Thanks, I'm trying to get it working, but I can't see if the language server has started or not.  Is there a log?

I think it's also being overridden by Webstorm's built-in JS and TS support.  The built-in stuff is buggy; is there a way to disable it or let the LSP plugin override it?

**Comment by gtache** [comment]
Should be fixed since 1.5.0

**Comment by fruddix** [comment]
Thanks for the multiple extension support. The Plugin gui suggest via quickinfo a comma separated list of file extensions (not a semicolon as mentioned here). This was confusing.
