### ISSUE TITLE
Add support for sending [initialized] message (LSP Spec 3.0)

### ISSUE THREAD

**Issue by gayanper** [gtache/intellij-lsp#34]
While trying to run the spring boot idea extension it was found out by the developer that the initialized message is not supported by this extension. More technical details are mentioned in https://github.com/spring-projects/sts4/issues/63 and https://microsoft.github.io/language-server-protocol/specification#initialized

**Comment by gayanper** [comment]
@gtache any update on this issue ?

**Comment by gayanper** [comment]
@gtache Any update on this ?

**Comment by gtache** [comment]
Sorry about the very long delay, I've added the initialized response in the 1.6.0 branch. I'm not sure if that was very easy or I'm doing something wrong yet.

**Comment by gayanper** [comment]
Yes it should be fairly easy. I tried this once and got it working. But i lost the working copy due to my pc crashed. I will try building and tryout with spring boot plugin

**Comment by gayanper** [comment]
I'm getting a compilation error when compiling this branch with java 8. Any special way this should be compiled ?

**Comment by gtache** [comment]
Yeah I'm not always checking that everything compiles on the dev branch, sorry about that.

[Here](https://drive.google.com/file/d/169nxkxfB0xE0xPfycBWYW6aI7Wtpl8ME/view?usp=sharing) is a Drive link to the LSP zip, it's too big to share in a GitHub conversation.    
Tell me if that works!

**Comment by gayanper** [comment]
I get the following errors, any way to get them solved
`Information:3/9/19 8:40 PM - Compilation completed with 3 errors and 0 warnings in 26 s 802 ms
/home/gayanper/Projects/idea-plugins/intellij-lsp/intellij-lsp/src/com/github/gtache/lsp/client/languageserver/requestmanager/RequestManager.scala
    Error:Error:line (14)overriding method typeDefinition in trait RequestManager of type (params: org.eclipse.lsp4j.TextDocumentPositionParams)java.util.concurrent.CompletableFuture[java.util.List[_ <: org.eclipse.lsp4j.Location]];
 method typeDefinition in trait TextDocumentService of type (x$1: org.eclipse.lsp4j.TextDocumentPositionParams)java.util.concurrent.CompletableFuture[org.eclipse.lsp4j.jsonrpc.messages.Either[java.util.List[_ <: org.eclipse.lsp4j.Location],java.util.List[_ <: org.eclipse.lsp4j.LocationLink]]] has incompatible type;
 (Note that method typeDefinition in trait RequestManager of type (params: org.eclipse.lsp4j.TextDocumentPositionParams)java.util.concurrent.CompletableFuture[java.util.List[_ <: org.eclipse.lsp4j.Location]] is abstract,
  and is therefore overridden by concrete method typeDefinition in trait TextDocumentService of type (x$1: org.eclipse.lsp4j.TextDocumentPositionParams)java.util.concurrent.CompletableFuture[org.eclipse.lsp4j.jsonrpc.messages.Either[java.util.List[_ <: org.eclipse.lsp4j.Location],java.util.List[_ <: org.eclipse.lsp4j.LocationLink]]]);
 other members with override errors are: implementation
trait RequestManager extends LanguageServer with TextDocumentService with WorkspaceService with LanguageClient {
/home/gayanper/Projects/idea-plugins/intellij-lsp/intellij-lsp/src/com/github/gtache/lsp/client/languageserver/requestmanager/SimpleRequestManager.scala
    Error:Error:line (300)overriding method implementation in trait TextDocumentService of type (x$1: org.eclipse.lsp4j.TextDocumentPositionParams)java.util.concurrent.CompletableFuture[org.eclipse.lsp4j.jsonrpc.messages.Either[java.util.List[_ <: org.eclipse.lsp4j.Location],java.util.List[_ <: org.eclipse.lsp4j.LocationLink]]];
 method implementation has incompatible type
  override def implementation(params: TextDocumentPositionParams): CompletableFuture[util.List[_ <: Location]] = throw new NotImplementedError()
    Error:Error:line (302)overriding method typeDefinition in trait TextDocumentService of type (x$1: org.eclipse.lsp4j.TextDocumentPositionParams)java.util.concurrent.CompletableFuture[org.eclipse.lsp4j.jsonrpc.messages.Either[java.util.List[_ <: org.eclipse.lsp4j.Location],java.util.List[_ <: org.eclipse.lsp4j.LocationLink]]];
 method typeDefinition has incompatible type
  override def typeDefinition(params: TextDocumentPositionParams): CompletableFuture[util.List[_ <: Location]] = throw new NotImplementedError()`

**Comment by gtache** [comment]
This happened when using "Install plugin from disk" and selecting the LSP.zip file? Have you tried uninstalling it first (maybe conflict with the plugin version)     
If this doesn't work, I'll release a version 1.5.4.

**Comment by gayanper** [comment]
Its was not due to the LSP plugin, i tried uninstalling as well. But looking at closely i found out that the following API needs to be changed as follows in RequestManager due to they are changed in TextDocumentService in the latest version that is getting imported to build.

``` scala
  override def implementation(params: TextDocumentPositionParams): CompletableFuture[messages.Either[util.List[_ <: Location], util.List[_ <: LocationLink]]] = throw new NotImplementedError()

  override def typeDefinition(params: TextDocumentPositionParams): CompletableFuture[messages.Either[util.List[_ <: Location], util.List[_ <: LocationLink]]] = throw new NotImplementedError()
```

**Comment by gayanper** [comment]
I think you need to tweak the place where you send the Initialized message because the current place the message will not be send due to the state is not started in SimpleRequestManager :). The following patch contains the compilation fix as well.

```diff
Index: intellij-lsp/src/com/github/gtache/lsp/client/languageserver/requestmanager/SimpleRequestManager.scala
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- intellij-lsp/src/com/github/gtache/lsp/client/languageserver/requestmanager/SimpleRequestManager.scala	(revision 7df0ae11f11ef83fe6416edea7a9ae44922436c3)
+++ intellij-lsp/src/com/github/gtache/lsp/client/languageserver/requestmanager/SimpleRequestManager.scala	(date 1552314735000)
@@ -7,6 +7,7 @@
 import com.github.gtache.lsp.client.languageserver.wrapper.LanguageServerWrapper
 import com.intellij.openapi.diagnostic.Logger
 import org.eclipse.lsp4j._
+import org.eclipse.lsp4j.jsonrpc.messages
 import org.eclipse.lsp4j.jsonrpc.messages.CancelParams
 import org.eclipse.lsp4j.services.{LanguageClient, LanguageServer, TextDocumentService, WorkspaceService}
 
@@ -297,9 +298,9 @@
         null
     } else null
 
-  override def implementation(params: TextDocumentPositionParams): CompletableFuture[util.List[_ <: Location]] = throw new NotImplementedError()
+  override def implementation(params: TextDocumentPositionParams): CompletableFuture[messages.Either[util.List[_ <: Location], util.List[_ <: LocationLink]]] = throw new NotImplementedError()
 
-  override def typeDefinition(params: TextDocumentPositionParams): CompletableFuture[util.List[_ <: Location]] = throw new NotImplementedError()
+  override def typeDefinition(params: TextDocumentPositionParams): CompletableFuture[messages.Either[util.List[_ <: Location], util.List[_ <: LocationLink]]] = throw new NotImplementedError()
 
   override def documentColor(params: DocumentColorParams): CompletableFuture[util.List[ColorInformation]] = throw new NotImplementedError()
 
Index: intellij-lsp/src/com/github/gtache/lsp/client/languageserver/requestmanager/RequestManager.scala
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- intellij-lsp/src/com/github/gtache/lsp/client/languageserver/requestmanager/RequestManager.scala	(revision 7df0ae11f11ef83fe6416edea7a9ae44922436c3)
+++ intellij-lsp/src/com/github/gtache/lsp/client/languageserver/requestmanager/RequestManager.scala	(date 1552314706000)
@@ -102,9 +102,9 @@
 
   override def rename(params: RenameParams): CompletableFuture[WorkspaceEdit]
 
-  override def implementation(params: TextDocumentPositionParams): CompletableFuture[java.util.List[_ <: Location]]
+  override def implementation(position: TextDocumentPositionParams): CompletableFuture[messages.Either[util.List[_ <: Location], util.List[_ <: LocationLink]]]
 
-  override def typeDefinition(params: TextDocumentPositionParams): CompletableFuture[java.util.List[_ <: Location]]
+  override def typeDefinition(position: TextDocumentPositionParams): CompletableFuture[messages.Either[util.List[_ <: Location], util.List[_ <: LocationLink]]]
 
   override def documentColor(params: DocumentColorParams): CompletableFuture[java.util.List[ColorInformation]]
 
Index: intellij-lsp/src/com/github/gtache/lsp/client/languageserver/wrapper/LanguageServerWrapperImpl.scala
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- intellij-lsp/src/com/github/gtache/lsp/client/languageserver/wrapper/LanguageServerWrapperImpl.scala	(revision 7df0ae11f11ef83fe6416edea7a9ae44922436c3)
+++ intellij-lsp/src/com/github/gtache/lsp/client/languageserver/wrapper/LanguageServerWrapperImpl.scala	(date 1552316640000)
@@ -346,9 +346,9 @@
         initializeFuture = languageServer.initialize(initParams).thenApply((res: InitializeResult) => {
           initializeResult = res
           LOG.info("Got initializeResult for " + serverDefinition + " ; " + rootPath)
+          setStatus(STARTED)
           requestManager = new SimpleRequestManager(this, languageServer, client, res.getCapabilities)
           requestManager.initialized(new InitializedParams()) //TODO That simple?
-          setStatus(STARTED)
           res
         })
         initializeStartTime = System.currentTimeMillis
```

**Comment by gayanper** [comment]
[0001-Working-fix-for-Initialized-and-compilation-fix.zip](https://github.com/gtache/intellij-lsp/files/2952942/0001-Working-fix-for-Initialized-and-compilation-fix.zip)

**Comment by gayanper** [comment]
@gtache when will you be able to release this support to intellij plugins repo ?

**Comment by gtache** [comment]
Glad you managed to make it work!     
It seems that for some reason it mixed some dependencies, 1.5.x is supposed to run on lsp4j 0.6.0 and 1.6.x will be on 0.7.0.

I just sent the update request, so it should be available in 1-2 days.

**Comment by gayanper** [comment]
So meanwhile which branch i can use to build locally ? 1.6.0 or master ?

**Comment by gtache** [comment]
That would be master
