### ISSUE TITLE
In webstorm: Menu items for "Code > Reformat code" are blank

### ISSUE THREAD

**Issue by mutech** [gtache/intellij-lsp#44]
After installing the plugin, the menu items for

* Reformat Code
* Show Reformat File Dialog

are blank (not greyed out). They still work though, as do the related short cuts.

When uninstalling the plugin the menu is shown again and disappears if the plugin is reinstalled.

Not a big deal, but strange and a bit annoying to find the plugin that is responsible for it.

**Comment by vobu** [comment]
need to re-open this: "Reformat Code" doesn't work any more once the lsp plugin is activated.

- macOS 10.14.5
- WebStorm 2019.1.3, Build #WS-191.7479.14, built on May 27, 2019
- JRE: 1.8.0_202-release-1483-b53 x86_64
- JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
