### ISSUE TITLE
Failing to build project, errors in build.sbt

### ISSUE THREAD

**Issue by tempit** [gtache/intellij-lsp#7]
Hi, trying to use this project to connect IntelliJ to my LSP server (https://github.com/wix/stylable-intelligence/), and having issues building the project. 
Getting this error, from wither command line or IntelliJ 'open Project' wizard:

 ~/p/intellij-lsp *master> sbt build.sbt     
[info] Loading project definition from /home/wix/projects/intellij-lsp/project
[error] [/home/wix/projects/intellij-lsp/build.sbt]:19: illegal start of simple expression
[error] [/home/wix/projects/intellij-lsp/build.sbt]:70: ')' expected but eof found.

Throwing the sbt file in an online Scala REPL (like https://scastie.scala-lang.org/) also throws the same errors.
Can you help please?

**Comment by gtache** [comment]
Hello, I just uploaded the first release. You have two main possibilities:    
-Download the zip of the first release and unzip it in your IDEA-U/ch-0/versionNumber/plugins folder (which would give plugins/LSP/lib/ folder structure), IntelliJ should then recognize the plugin.    
-Wait one/two days for JetBrains to approve the plugin and you will be able to install it directly from IntelliJ    

Hope it will work for you and the development of your server will go nicely!
